config/routes.rb
JakesLinkOTheDay::Application.routes.draw do
  resources :jakeslinks

  resources :topic2s

end

app/models/jakeslink.rb
class Jakeslink < ActiveRecord::Base
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/topic2.rb
class Topic2 < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/jakeslinks_controller.rb
class JakeslinksController < ApplicationController
  # GET /jakeslinks
  # GET /jakeslinks.json
  def index
    @jakeslinks = Jakeslink.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jakeslinks }
    end
  end

  # GET /jakeslinks/1
  # GET /jakeslinks/1.json
  def show
    @jakeslink = Jakeslink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @jakeslink }
    end
  end

  # GET /jakeslinks/new
  # GET /jakeslinks/new.json
  def new
    @jakeslink = Jakeslink.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @jakeslink }
    end
  end

  # GET /jakeslinks/1/edit
  def edit
    @jakeslink = Jakeslink.find(params[:id])
  end

  # POST /jakeslinks
  # POST /jakeslinks.json
  def create
    @jakeslink = Jakeslink.new(params[:jakeslink])

    respond_to do |format|
      if @jakeslink.save
        format.html { redirect_to @jakeslink, notice: 'Jakeslink was successfully created.' }
        format.json { render json: @jakeslink, status: :created, location: @jakeslink }
      else
        format.html { render action: "new" }
        format.json { render json: @jakeslink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jakeslinks/1
  # PUT /jakeslinks/1.json
  def update
    @jakeslink = Jakeslink.find(params[:id])

    respond_to do |format|
      if @jakeslink.update_attributes(params[:jakeslink])
        format.html { redirect_to @jakeslink, notice: 'Jakeslink was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @jakeslink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jakeslinks/1
  # DELETE /jakeslinks/1.json
  def destroy
    @jakeslink = Jakeslink.find(params[:id])
    @jakeslink.destroy

    respond_to do |format|
      format.html { redirect_to jakeslinks_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/topic2s_controller.rb
class Topic2sController < ApplicationController
  # GET /topic2s
  # GET /topic2s.json
  def index
    @topic2s = Topic2.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topic2s }
    end
  end

  # GET /topic2s/1
  # GET /topic2s/1.json
  def show
    @topic2 = Topic2.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic2 }
    end
  end

  # GET /topic2s/new
  # GET /topic2s/new.json
  def new
    @topic2 = Topic2.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic2 }
    end
  end

  # GET /topic2s/1/edit
  def edit
    @topic2 = Topic2.find(params[:id])
  end

  # POST /topic2s
  # POST /topic2s.json
  def create
    @topic2 = Topic2.new(params[:topic2])

    respond_to do |format|
      if @topic2.save
        format.html { redirect_to @topic2, notice: 'Topic2 was successfully created.' }
        format.json { render json: @topic2, status: :created, location: @topic2 }
      else
        format.html { render action: "new" }
        format.json { render json: @topic2.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topic2s/1
  # PUT /topic2s/1.json
  def update
    @topic2 = Topic2.find(params[:id])

    respond_to do |format|
      if @topic2.update_attributes(params[:topic2])
        format.html { redirect_to @topic2, notice: 'Topic2 was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic2.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topic2s/1
  # DELETE /topic2s/1.json
  def destroy
    @topic2 = Topic2.find(params[:id])
    @topic2.destroy

    respond_to do |format|
      format.html { redirect_to topic2s_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jakeslinks_helper.rb
module JakeslinksHelper
end

app/helpers/topic2s_helper.rb
module Topic2sHelper
end

app/views/jakeslinks/_form.html.erb
<%= form_for(@jakeslink) do |f| %>
  <% if @jakeslink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jakeslink.errors.count, "error") %> prohibited this jakeslink from being saved:</h2>

      <ul>
      <% @jakeslink.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_area :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jakeslinks/edit.html.erb
<h1>Editing jakeslink</h1>

<%= render 'form' %>

<%= link_to 'Show', @jakeslink %> |
<%= link_to 'Back', jakeslinks_path %>

app/views/jakeslinks/index.html.erb
<h1>Listing jakeslinks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Url</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @jakeslinks.each do |jakeslink| %>
  <tr>
    <td><%= jakeslink.name %></td>
    <td><%= jakeslink.url %></td>
    <td><%= link_to 'Show', jakeslink %></td>
    <td><%= link_to 'Edit', edit_jakeslink_path(jakeslink) %></td>
    <td><%= link_to 'Destroy', jakeslink, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Jakeslink', new_jakeslink_path %>

app/views/jakeslinks/new.html.erb
<h1>New jakeslink</h1>

<%= render 'form' %>

<%= link_to 'Back', jakeslinks_path %>

app/views/jakeslinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @jakeslink.name %>
</p>

<p>
  <b>Url:</b>
  <%= @jakeslink.url %>
</p>


<%= link_to 'Edit', edit_jakeslink_path(@jakeslink) %> |
<%= link_to 'Back', jakeslinks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jake's Link O' The Day</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/topic2s/_form.html.erb
<%= form_for(@topic2) do |f| %>
  <% if @topic2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic2.errors.count, "error") %> prohibited this topic2 from being saved:</h2>

      <ul>
      <% @topic2.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topic2s/edit.html.erb
<h1>Editing topic2</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic2 %> |
<%= link_to 'Back', topic2s_path %>

app/views/topic2s/index.html.erb
<h1>Listing topic2s</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topic2s.each do |topic2| %>
  <tr>
    <td><%= topic2.title %></td>
    <td><%= topic2.description %></td>
    <td><%= link_to 'Show', topic2 %></td>
    <td><%= link_to 'Edit', edit_topic2_path(topic2) %></td>
    <td><%= link_to 'Destroy', topic2, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic2', new_topic2_path %>

app/views/topic2s/new.html.erb
<h1>New topic2</h1>

<%= render 'form' %>

<%= link_to 'Back', topic2s_path %>

app/views/topic2s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @topic2.title %>
</p>

<p>
  <b>Description:</b>
  <%= @topic2.description %>
</p>


<%= link_to 'Edit', edit_topic2_path(@topic2) %> |
<%= link_to 'Back', topic2s_path %>